image: node:latest

stages:
    - build
    - test
    - staging
    - production

cache:
 paths:
  - node_modules/

.only-default: &only-default
 only:
  - master
  - develop
  - staging
  - merge_requests

build:
  <<: *only-default
  stage: build
  tags:
    - runner-deploy-heroku
  script:
    - npm install

test:
  only:
    - merge_requests
  stage: test
  tags:
    - runner-deploy-heroku
  artifacts:
    paths:
      - bin/
  script:
    - npm install
    - npm test

staging:
  type: deploy
  stage: staging
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
    - staging
  tags:
    - runner-deploy-heroku

production:
  type: deploy
  stage: production
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - master
  tags:
    - runner-deploy-heroku
    
